#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -r proc*

application=$(getApplication)

blockMesh

decomposePar
mpirun -np 4 $application -parallel
reconstructPar

#------------------------------------------------------------------------------
