#!/bin/sh
cd "${0%/*}" || exit 1    # Run from this directory

fluentMeshToFoam '/home/ehsan/Desktop/session3/CCACase/52k352.msh'

transformPoints -scale '(0.01 0.01 0.01)'

simpleFoam

postProcess -func streamFunction

#------------------------------------------------------------------------------
