#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# (getApplication) is an command to find the solver name from the controlDict file. Also, ($) use for the variable.
application=$(getApplication)

RPM=10
omega=`echo $RPM*0.1047 | bc -l`

curdir= pwd
rm -r $curdir'constant/polyMesh'
fluent3DMeshToFoam $curdir'constant/baseMesh.msh'
snappyHexMesh -overwrite
createPatch -overwrite
transformPoints -scale '(0.001 0.001 0.001)'

sed -i "s/omegaCase/$omega/"	$curdir'constant/MRFProperties'


echo solving...
$application




